export const CARD_ADD_ITEM = 'CARD_ADD_ITEM';
export const CARD_REMOVE_ITEM = 'CARD_REMOVE_ITEM';
export const CARD_SAVE_SHIPPING = 'CARD_SAVE_SHIPPING';
export const CARD_SAVE_PAYMENTMETHOD = 'CARD_SAVE_PAYMENTMETHOD';
